blog/urls.py
'''
Created on 2019年11月5日

@author: xwx
'''
from django.urls import path
from blog import views
#命名空间
app_name='blog'
urlpatterns = [
    path('', views.index, name='index'),  # 网站首页
    path('article', views.article, name='article'),
    path('article_detail/<int:sid>', views.article_detail, name='article_detail'),  # 内容页
    path('about/', views.about, name='about'),  # 联系我们单页
]

myblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from blog import views
from myblog import settings

urlpatterns = [
    path('admin/', admin.site.urls),#管理后台
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('photologue/', include('photologue_custom.urls', namespace='photologue_custom')),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#开发环境下使用

photologue_custom/urls.py
from django.urls import path

from photologue_custom import views

app_name='photologue_custom'
urlpatterns = [
    path('gallery', views.gallery, name='gallery'),
    path('gallery_detail/<int:gid>', views.gallery_detail, name='gallery_detail'),
    # path('diggit', views.diggit, name='diggit'),
    path('gallerys', views.gallerys.as_view(), name='gallerys'),
]

blog/models.py
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_delete, post_init, post_save
from django.dispatch import receiver
from blog.storage import UploadStorage
# 导入Django自带用户模块

# 文章分类


class Category(models.Model):
    name = models.CharField('博客分类', max_length=100)
    index = models.IntegerField(default=999, verbose_name='分类排序')

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=100)

    class Meta:
        verbose_name = '文章标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 推荐位
class Tui(models.Model):
    name = models.CharField('推荐位', max_length=100)

    class Meta:
        verbose_name = '推荐位'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 文章
class Article(models.Model):
    title = models.CharField('标题', max_length=70)
    excerpt = models.TextField('摘要', max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, verbose_name='分类')
    # 使用外键关联分类表与分类是一对多关系
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)
    # 使用外键关联标签表与标签是多对多关系
    img = models.ImageField(storage=UploadStorage(), verbose_name='文章图片', blank=True, null=True)
    body = RichTextUploadingField('正文')
    likes = models.PositiveIntegerField('点赞量', default=0)

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')
    """
    文章作者，这里User是从django.contrib.auth.models导入的。
    这里我们通过 ForeignKey 把文章和 User 关联了起来。
    """
    views = models.PositiveIntegerField('阅读量', default=0)
    tui = models.ForeignKey(Tui, on_delete=models.DO_NOTHING, verbose_name='推荐位', blank=True, null=True)

    created_time = models.DateTimeField('发布时间', auto_now_add=True)
    modified_time = models.DateTimeField('修改时间', auto_now=True)


    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'


    def __str__(self):
        return self.title


#删除时
@receiver(pre_delete, sender=Article)
def delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.img.delete(False)
#修改时
@receiver(post_init, sender=Article)
def image_path(sender, instance, **kwargs):
    instance._current_file = instance.img
@receiver(post_save, sender= Article)
def delete_old_image(sender, instance, **kwargs):
    if hasattr(instance, '_current_file'):
        if instance.img:
            if instance._current_file != instance.img.path:
                instance._current_file.delete(save=False)


# 友情链接
class Link(models.Model):
    name = models.CharField('链接名称', max_length=20)
    linkurl = models.URLField('网址', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = '友情链接'

photologue_custom/models.py
from django.db import models

# Create your models here.
from photologue.models import Gallery


# class Gallery(Gallery):
#     likes = models.PositiveIntegerField('点赞量', default=0)

blog/views.py
from django.db.models import Q
from django.shortcuts import render

# Create your views here.
from photologue.models import Gallery

from blog.models import Category, Article, Tag, Link
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

#首页
def index(request):
    allcategory = Category.objects.all()
    gallerys = Gallery.objects.all().order_by('-id')[0:6]
    tui = Article.objects.filter(tui__id=1)[:5]
    allarticle = Article.objects.all().order_by('-id')[0:10]
    hot = Article.objects.all().order_by('views')[:5]
    link = Link.objects.all()
    return render(request, 'index.html', locals())

#列表页
def article(request):
    page = request.GET.get('page', 1)
    keyword = request.GET.get('keyword', '')
    allcategory = Category.objects.all()
    tags = Tag.objects.all()
    tui = Article.objects.filter(tui__id=1)[:5]
    allarticle = Article.objects.filter(Q(title__contains=keyword) | Q(excerpt__contains=keyword)).order_by('-id')
    paginator = Paginator(allarticle, 10)
    try:
        allarticle = paginator.page(page)#获取当前页码的记录
    except PageNotAnInteger:
        allarticle = paginator.page(1)#如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        allarticle = paginator.page(paginator.num_pages)#如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容
    return render(request, 'article.html', locals())


#内容页
def article_detail(request,sid):
    detail = Article.objects.get(id=sid)
    hot = Article.objects.all().order_by('?')[:10]
    previous_blog = Article.objects.filter(created_time__gt=detail.created_time,category=detail.category.id).first()
    netx_blog = Article.objects.filter(created_time__lt=detail.created_time,category=detail.category.id).last()
    detail.views = detail.views + 1
    detail.save()
    return render(request, 'article_detail.html', locals())


# 关于我们
def about(request):
    return render(request, 'about.html',locals())

photologue_custom/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from photologue.models import Gallery
from rest_framework.response import Response
from rest_framework.views import APIView

from blog.models import Category, Tag, Article
from photologue_custom.serializers import GallerySerializers


def gallery(request):
    page = request.GET.get('page', 1)
    gallerys = Gallery.objects.filter(is_public=True).order_by('-id')
    paginator = Paginator(gallerys, 8)
    try:
        gallerys = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        gallerys = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        gallerys = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容
    return render(request, 'gallery.html', locals())

def gallery_detail(request, gid):
    hot = Article.objects.all().order_by('views')[:5]
    allcategory = Category.objects.all()
    tags = Tag.objects.all()
    tui = Article.objects.filter(tui__id=1)[:5]
    gallery = Gallery.objects.get(Q(is_public=True) & Q(pk=gid))
    return render(request, 'gallery_detail.html', locals())

def diggit(request):
    data = {'state': 200, 'msg': None}
    return JsonResponse(data)


class gallerys(APIView):

    def get(self, request):
        page = request.GET.get('page', 1)
        gallery = Gallery.objects.all()[(page-1)*8:page*8]
        data = GallerySerializers(gallery, context={'request': request}, many=True)
        return Response(data.data)

blog/templates/about.html
{% extends "base.html" %}

{% block left %}
{% include 'left_follow.html' %}
{% include 'left.html' %}

 {% endblock %}
{% block content %}
<main class="r_box">
     <ul class="about">
      <p>周淑燕</p>

     </ul>
  </main>

{% endblock %}

blog/templates/article.html
{% extends "base.html" %}
{% block left %}

{% include 'left.html' %}
{% include 'left_tag.html' %}
           {% endblock %}
{% block content %}
{% include 'article_list.html' %}
        </article>
{% endblock %}

blog/templates/article_detail.html
{% extends "base.html" %}
{% block static %}
<link href="{% static 'css/info.css' %}" rel="stylesheet">
{% endblock %}
{% block left %}

{% include 'left.html' %}
{% include 'left_tag.html' %}
     {% endblock %}
{% block content %}
    <main class="infosbox">
    <div class="newsview">
      <h3 class="news_title">{{ detail.title }}</h3>
      <div class="bloginfo">
        <ul>
          <li class="author">作者：<a href="/">{{ detail.user.username }}</a></li>
          <li class="lmname"><a href="/">{{ detail.category.name }}</a></li>
          <li class="timer">时间：{{ detail.created_time }}</li>
          <li class="view">{{ detail.views }}人已阅读</li>
        </ul>
      </div>
<div class="tags">
     {% for tag in detail.tags.all %}
        <a href="/" target="_blank">{{ tag.name }}</a>
     {% endfor %}


      <div class="news_about"><strong>简介</strong>{{ detail.excerpt }}</div>
      <div class="news_con">
          {%autoescape off%}
          {{ detail.body }}
          {% endautoescape %}
        &nbsp; </div>
    </div>
    <a href="javascript:void(0);"><div class="share">
      <p class="diggit"> 很赞哦！ </a>(<b id="diggnum">{{ detail.likes }}</b>)</p>
    </div></a>
    <div class="nextinfo">
      <p>上一篇：{% if previous_blog %}
      <a href="{% url 'blog:article_detail' previous_blog.id %}">{{ previous_blog.title }}</a></p>
          {% else %} 没有了
      {% endif %}
      <p>下一篇：{% if netx_blog %}
          <a href="{% url 'blog:article_detail' netx_blog.id %}">{{ netx_blog.title }}</a></p>
    {% else %} 没有了
      {% endif %}
    </div>
    <div class="news_pl">
      <h2>文章评论</h2>
      <ul>
        <div class="gbko"> </div>
      </ul>
    </div>
    </div>
      </main>
    <script>
        {# 点赞和踩 ，两个标签加上action  is_up为布尔值 #}
        $('.share').click(function () {
            var is_up = $(this).hasClass('diggit')
            {# ajax来操作点赞功能 #}
{#            $.ajax({#}
{#                url: '{% url 'photologue_custom:diggit' %}',#}
{#                type: 'get',#}
{#                data: {#}
{#                    'gid': '{{ gallery.pk }}',#}
{#                },#}
{#                success: function (data) {#}
{#                    if (data.state) {#}
{#                        // Ajax 局部刷新!!!#}
            var val = parseInt($('#diggnum').text());
            $('#diggnum').text(val+1)
{#                    }#}
  {#               }#}
   {#          })#}
        })

    </script>
{% endblock %}

blog/templates/article_list.html
<main class="r_box">
    {%for article in allarticle%}
                <li>

                        {% if article.img %}
                    <i><a href="{% url 'blog:article_detail' article.id %}">
                        <img src="{{ article.img.url }}"></a></i>
                        {% endif %}

      <h3><a href="{% url 'blog:article_detail' article.id %}">{{ article.title }}</a></h3>
      <p>{{ article.excerpt }}</p>
    </li>
            {%endfor%}

{% if allarticle.paginator %}
        <div class="pagelist">
            {% if page != 1 %}
        <a class="allpage" href="{% url 'blog:article' %}?keyword={{ keyword }}"><b>首页</b></a>
        {% endif %}
            {% if allarticle.has_previous %}<a href="{% url 'blog:article' %}?keyword={{ keyword }}&page={{ allarticle.previous_page_number }}" onclick="page(2)">上一页</a>{% endif %}


            <a href="#" class="curPage">{{ page }}</a>

            {% if allarticle.has_next %}<a href="{% url 'blog:article' %}?keyword={{ keyword }}&page={{ allarticle.next_page_number }}" onclick="page(2)">下一页</a>{% endif %}
            {% if allarticle.next_page_number == allarticle.num_pages %}
        <a class="allpage" href="{% url 'blog:article' %}?keyword={{ keyword }}&page={{ allarticle.num_pages }}"><b>尾页</b></a>
        {% endif %}

        </div>
{% endif %}
  </main>

blog/templates/base.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_周淑燕个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,周淑燕个人博客,个人博客模板,周淑燕" />
<meta name="description" content="周淑燕个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<link href="{% static 'css/index.css' %}" rel="stylesheet">
<link href="{% static 'css/m.css'%}" rel="stylesheet">
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    {% block static %}
    {% endblock %}

<script type="text/javascript" src="{% static 'js/hc-sticky.js' %}"></script>
<script type="text/javascript" src="{% static 'js/comm.js' %}"></script>

<!--[if lt IE 9]>
<script src="{% static 'js/modernizr.js' %}"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">周淑燕个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{% url 'blog:index' %}">网站首页</a></li>
      <li><a href="{% url 'photologue_custom:gallery' %}">我的相册</a></li>
      <li><a href="{% url 'blog:article' %}">我的日记</a></li>
      <li><a href="{% url 'blog:about' %}">关于我</a></li>
    </ul>
</nav>
</header>
    <article>
  <aside class="l_box">
{% block left %}

{% endblock %}
</aside>
{% block content %}

{% endblock %}
</article>
<footer>
  <p>Design by <a href="#" target="_blank">周淑燕个人博客</a> <a href="/">蜀ICP备XXXXXXXXX号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>

blog/templates/index.html
{% extends "base.html" %}
{% block left %}

{% include 'left_about.html' %}
{% include 'left.html' %}

{% include 'left_follow.html' %}
<div class="links">
        <h2>友情链接</h2>
        {% for i in link %}
            <ul>
              <a href="{{ linkurl }}">{{ name }}</a>
            </ul>
        {% endfor %}
      </div>
 {% endblock %}
{% block content %}
{% include 'article_list.html' %}

{% endblock %}

blog/templates/left.html
<div class="search">
        <form action="article" method="get" name="searchform" id="searchform">
            {% csrf_token %}
          <input name="keyword" id="keyword" class="input_text" value="{{ keyword }}" style="color: rgb(153, 153, 153);" type="text">

          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
<div class="fenlei">
        <h2>文章分类</h2>
        <ul>
            {%for category in allcategory%}
                <li><a href="/">{{ category.name }}</a></li>
            {%endfor%}
        </ul>
      </div>
<div class="tuijian">
        <h2>站长推荐</h2>
        <ul>
            {%for t in tui%}
                <li><a href="/">{{ t.title }}</a></li>
            {%endfor%}
        </ul>
      </div>
<div class="tuijian">
      <h2>点击排行</h2>
      <ul>
        {%for h in hot%}
                <li><a href="/">{{ h.title }}</a></li>
        {%endfor%}
      </ul>
    </div>

blog/templates/left_about.html
{% load filters %}
<div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="{% static 'images/4.jpg' %}"></i>
          <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
        </ul>
      </div>
{% if gallerys %}
    <div class="wdxc">
            <h2>我的相册</h2>
           <ul>
                {%for gallery in gallerys %}

                   <li><a href="{% url 'photologue_custom:gallery_detail' gallery.id %}"><img src="{{ gallery | img }}"></a></li>
                {%endfor%}
           </ul>
          </div>
{% endif %}

blog/templates/left_follow.html
<div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="{% static 'images/wx.jpg' %}">
        </ul>
      </div>

blog/templates/left_tag.html
<div class="cloud">
      <h2>标签云</h2>
      <ul>
          {% for tag in tags %}
            <a href="/">{{ tag.name }}</a>
          {% endfor %}

      </ul>
    </div>

photologue_custom/templates/gallery.html
{% extends "base.html" %}
{% load filters %}

{% block content %}
<div class="picbox">
    {% for gallery in gallerys %}
        <ul>
      <li data-scroll-reveal="enter bottom over 1s" ><a href="{% url 'photologue_custom:gallery_detail' gallery.id %}"><i><img src="{{ gallery | img }}"></i>
        <div class="picinfo">
          <h3>{{ gallery.title }}</h3>
          <span>{{ gallery.description }}</span> </div>
        </a></li>
    </ul>
    {% endfor %}


  </div>
<div class="pagelist">
            {% if page != 1 %}
        <a class="allpage" href="{% url 'photologue_custom:gallery' %}"><b>首页</b></a>
        {% endif %}
            {% if gallerys.has_previous %}<a href="{% url 'photologue_custom:gallery' %}?page={{ gallerys.previous_page_number }}" onclick="page(2)">上一页</a>{% endif %}


            <a href="#" class="curPage">{{ page }}</a>

            {% if gallerys.has_next %}<a href="{% url 'photologue_custom:gallery' %}?page={{ gallerys.next_page_number }}" onclick="page(2)">下一页</a>{% endif %}
            {% if gallerys.next_page_number == gallerys.num_pages %}
        <a class="allpage" href="{% url 'photologue_custom:gallery' %}?page={{ gallerys.num_pages }}"><b>尾页</b></a>
        {% endif %}

        </div>
  {% endblock %}

photologue_custom/templates/gallery_detail.html
{% extends "base.html" %}

{% block static %}
<link href="{% static 'css/infopic.css' %}" rel="stylesheet">
<script src="{% static 'js/piccontent.min.js' %}" type="text/javascript"></script>
    {% endblock %}
{% block left %}
{% include 'left.html' %}
{% endblock %}
{% block content %}

<main>
  <div class="picsbox">
    <div class="bodymodal"></div>
    {#播放到第一张图的提示#}
    <div class="firsttop">
      <div class="firsttop_right">
        <div class="close2"> <a class="closebtn1" title="关闭" href="javascript:void(0)"></a> </div>
        <div class="replay">
          <h2 id="div-end-h2"> 已到第一张图片了。 </h2>
          <p> <a class="replaybtn1" href="javascript:;">重新播放</a> </p>
        </div>
      </div>
    </div>
    {#播放到最后一张图的提示#}
    <div class="endtop">
      <div class="firsttop_right">
        <div class="close2"> <a class="closebtn2" title="关闭" href="javascript:void(0)"></a> </div>
        <div class="replay">
          <h2 id="H1"> 已到最后一张图片了。 </h2>
          <p> <a class="replaybtn2" href="javascript:;">重新播放</a> </p>
        </div>
      </div>
    </div>
    {#弹出层结束#}
    {#图片特效内容开始#}
    <div class="piccontext">
      <h2> {{ gallery.title }} </h2>
      <div class="source">
        <div class="source_left"><span>{{ gallery.date_added }}</span> </div>
        <div class="source_right"> <a href="javascript:;" class="list">列表查看</a> </div>
        <div class="source_right1"> <a href="javascript:;" class="gaoqing">高清查看</a> </div>
      </div>
      {#大图展示#}
      <div class="picshow">
        <div class="picshowtop"> <a href="#"><img src="" alt="" id="pic1" curindex="0" /></a> <a id="preArrow" href="javascript:void(0)" class="contextDiv" title="上一张"><span id="preArrow_A"></span></a> <a id="nextArrow" href="javascript:void(0)" class="contextDiv" title="下一张"><span id="nextArrow_A"></span></a> </div>
        <div class="picshowtxt">
          <div class="picshowtxt_left"><span>1</span>/<i>12</i></div>
          <div class="picshowtxt_right"></div>
        </div>
        <div class="picshowlist">
          <div class="picshowlist_mid">
            <div class="picmidleft"> <a href="javascript:void(0)" id="preArrow_B"><span class="sleft"></span></a> </div>
            <div class="picmidmid">
              <ul>
                {% for photo in gallery.sample %}
                  <li> <a href="javascript:void(0);"><img src="{{ photo.get_thumbnail_url }}" alt="" bigimg="{{ photo.image.url }}" text="{{ photo.title }}" /></a></li>
                {% endfor %}
              </ul>
            </div>
            <div class="picmidright"> <a href="javascript:void(0)" id="nextArrow_B"><span class="sright"></span></a> </div>
          </div>
        </div>
      </div>

      {#列表展示#}
      <div class="piclistshow">
        <ul>
          {% for photo in gallery.sample %}
            <li>
              <div class="picimg"><img src="{{ photo.get_display_url }}" alt="" /></div>
              <div class="pictxt">
                <h3>{{ photo.title }}</h3>
              </div>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="pictext">
      <ul>
        {{ gallery.description }}
      </ul>
    </div>
    <a href="javascript:void(0);"><div class="share">
      <p class="diggit"> 很赞哦！(<b id="diggnum">13</b>)</p>
    </div></a>
  </div>
  </main>
    <script>
        {# 点赞和踩 ，两个标签加上action  is_up为布尔值 #}
        $('.share').click(function () {
            var is_up = $(this).hasClass('diggit')
            {# ajax来操作点赞功能 #}
{#            $.ajax({#}
{#                url: '{% url 'photologue_custom:diggit' %}',#}
{#                type: 'get',#}
{#                data: {#}
{#                    'gid': '{{ gallery.pk }}',#}
{#                },#}
{#                success: function (data) {#}
{#                    if (data.state) {#}
{#                        // Ajax 局部刷新!!!#}
            var val = parseInt($('#diggnum').text());
            $('#diggnum').text(val+1)

{#                    }#}
  {#               }#}
   {#          })#}
        })

    </script>
{% endblock %}